FROM python:3.10-alpine

#Create directories
# -p for creating nested dirs
RUN 
    mkdir /model && \
    mkdir /model/src && \
    mkdir -p /model/data/03_transformed && \
    mkdir /model/results && \
    mkdir /model/logs

#change workdir to /model
WORKDIR /model

#Copy files
COPY main.py .
COPY ./src/* ./src/
COPY ./data/03_transformed/output_transformed.csv ./data/03_transformed/
COPY requirements.txt .

#Install dependencies
RUN pip install -r requirements.txt

#run main.py, ignore warnings (so they dont get logged)
CMD ["python", "-W", "ignore", "main.py"] 